export const locale = {
"eng_US" : { 
	hello: "Hello",
	email: "Email",
	logIn: "Log In",
	signUp: "Sign Up",
	ModalPhone: "The verification code has been sent",
	ForgotPasword: "Forgot passord ?",
	EnterFirstname: "Enter Firstname",
	EnterLastName: "Enter LastName",
	EnterEmail: "Enter Email",
	EnterPassword: "Enter Password",
	Iagreeto: "I agree to",
	PrivacyPolicy: "Privacy Policy",
	TermsofUse: "Terms of Use",
	PleaseFill: "Please fill in this form to create an account.",
	PhoneNumber: "Phone Number",
	Sendverificationcode: "Send verification code",
	LogIn: "Log In",
	EnterYourCredentials: "Enter your credentials",
	OR: "OR",
	ModalEmail: "The email was send",
	ModalPhone: "The verification code has been sent",
	PlzEndterEmail: "Please enter your email address we'll send you a link to change the password",
	sendForgotEmail: "Email is invalid",
	sendEmai: "Send Email",
	Invalidlogin: "Invalid login / password",
	invalidPhone: "Phone number is invalid",
	invFirstName: "Firstname is required",
	invLastName: "Lastnane is required",
	invEmail: "Email invalid",
	invPsw: "Password mustbe at list 6 characters long",
	invCheckBox: "Please checke checkbox",
	GetStarted: "Get Started",
	TestPage: "Test auth page",
	usedEmail: "Email is already used",
	LogOut: "Log Out"
	},
"ua_UA" : {
	hello: "Привіт",
	email: "Імейл",
	logIn: "Увійти",
	signUp: "Зареєструватися",
	ModalPhone: "Код підтвердження було відправлено",
	ForgotPasword: "Забули пароль ?",
	EnterFirstname: "Введіть Ім'я",
	EnterLastName: "Введіть Фамілію",
	EnterEmail: "Введіть Імейл",
	EnterPassword: "Введіть пароль",
	Iagreeto: "Я згоден з",
	PrivacyPolicy: "політикою приватності",
	TermsofUse: "умовами використання",
	PleaseFill: "Будь ласка заповніть форму для створення аккаунту",
	EnterYourCredentials: "Уведіть свої данні",
	Sendverificationcode: "Надіслати код підтвердження",
	PhoneNumber: "Номер телефону",
	OR: "Чи",
	LogIn: "Увійти",
	ModalEmail: "Листа було відправлено",
	ModalPhone: "Код підтвердження було відправлено",
	PlzEndterEmail: "Введіть свій імейл і ми відправимо вам посилання на зміну пароля",
	sendForgotEmail: "Імейл не валідний",
	sendEmai: "Відправити імейл",
	Invalidlogin: "Невірний логін / пароль",
	invalidPhone: "Номер телефону невалідний",
	invFirstName: "Ім'я обов'язкове",
	invLastName: "Фамілія обов'зкова",
	invEmail: "Імейл невалідний",
	invPsw: "Пароль має бути мінімум 6 символів",
	invCheckBox: "Оберіть чекбокс",
	TestPage: "Тестова сторінка",
	GetStarted: "Почати",
	usedEmail: "Імейл уже зареєстровано",
	LogOut: "Вийти"
	}
}

